name: scenicplus_fixed
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn
  - pandas
  - pyranges
  - pip
  - pip:
    - pycisTopic
    - scrublet
